# Local Ollama - Fully offline, private deployment
# All data stays on your machine. No API key required.
#
# IMPORTANT: You must have Ollama installed and models pulled locally.
# The models below are SUGGESTIONS - replace with what you have installed.
#
# To check available models: ollama list
# To pull a model: ollama pull <model>
#
# Recommended models to pull:
#   ollama pull qwen2.5-coder:32b    # Most capable coding model
#   ollama pull qwen2.5-coder:7b     # Standard coding model
#   ollama pull qwen2.5-coder:1.5b   # Fast budget model
#
# Alternative suggestions:
#   ollama pull deepseek-coder-v2:latest  # Great for code
#   ollama pull llama3.2:latest           # General purpose
#   ollama pull codellama:latest          # Code-focused
#
name: local
description: Local Ollama models - offline/private, customize to your installed models

# Default model for the main opencode.json "model" field
default_model: ollama/qwen2.5-coder:7b

# Agent routing with model tiers (CUSTOMIZE THESE!)
agents:
  Algorithm:
    model: ollama/qwen2.5-coder:32b
  Architect:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  Engineer:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  general:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  explore:
    model: ollama/qwen2.5-coder:1.5b
  Intern:
    model: ollama/qwen2.5-coder:1.5b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:1.5b
      advanced: ollama/qwen2.5-coder:7b
  Writer:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  DeepResearcher:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  GeminiResearcher:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  GrokResearcher:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  PerplexityResearcher:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  CodexResearcher:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  QATester:
    model: ollama/qwen2.5-coder:7b
  Pentester:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  Designer:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
  Artist:
    model: ollama/qwen2.5-coder:7b
    tiers:
      quick: ollama/qwen2.5-coder:1.5b
      standard: ollama/qwen2.5-coder:7b
      advanced: ollama/qwen2.5-coder:32b
